package service.basicFunctions;

public enum OperationFlags {
	USER_EXTRA_ATTRIBUTE_CONFIG_ADD,
	USER_EXTRA_ATTRIBUTE_CONFIG_REMOVE,
	USER_EXTRA_ATTRIBUTE_CONFIG_UPDATE,
	USER_EXTRA_ATTRIBUTE_ADD,
	USER_EXTRA_ATTRIBUTE_REMOVE,
	USER_EXTRA_ATTRIBUTE_UPDATE,
	USER_EXTRA_ATTRIBUTE_GET,
}
